# Uncomment the lines below you want to change by removing the # in the beginning

# Delete and re-create iOS simulator
erase_simulator true

stop_after_first_error false

number_of_retries 2

ios_version "10.3"

# A list of devices you want to take the screenshots from
devices([
	# "iPhone 4s",
	"iPhone SE",
 	"iPhone 7",
  	"iPhone 7 Plus",
  	"iPad Pro (9.7 inch)",
  	"iPad Pro (12.9 inch)"
])

languages([
  ["pt", "pt_BR"], # Portuguese with Brazilian locale
  "en-US"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# The name of the scheme which contains the UI Tests
scheme ""

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots false # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./YourAppTarget.xcworkspace"

# For more information about all available options run
# snapshot --help