# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

default_platform :ios

platform :ios do

	before_all do
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
    cocoapods
    #reset_simulators
  end

	lane :tests do
    scan
  end

  lane :screenshots do
    snapshot
  end

  lane :certs do
    cert(
      development: false,
      username: "", # your developer account email
      output_path: "./fastlane/certs"
    )
    sigh(
      development: false,
      username: "", # your developer account email
      app_identifier: "", # the bundle identifier of your app
      output_path: "./fastlane/certs"
    )
  end

  desc "Runs all the tests"
  desc "Take screenshots"
  desc "Install certificates and provisions"
  desc "Create build"
  lane :build do
    tests
    screenshots
    certs
    gym
  end
	
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    build
    pilot
    # sh "your_script.sh"
  end

	desc "Deploy a new version to the App Store"
  lane :store do
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    build
    deliver
  end

	after_all do |lane|
        
  end

  error do |lane, exception|
        
  end

end